In [1]:
import pandas as pd
import numpy as np

print("ETL environment ready!")

ETL environment ready!

In [5]:
df = pd.read_csv("../data_raw/Sample - Superstore")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data_raw/Sample - Superstore'

In [6]:
df = pd.read_csv("../data_raw/Superstore.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data_raw/Superstore.csv'

In [7]:

df = pd.read_csv("../data_raw/Superstore.csv")
df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2944: invalid start byte

In [8]:
import os
os.listdir("../data_raw")

['Superstore.csv']

In [9]:
import os
os.getcwd()

'C:\\Users\\User\\Downloads\\BI Project\\etl'

In [10]:
import pandas as pd

df = pd.read_csv("../data_raw/Superstore.csv")
df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2944: invalid start byte

In [11]:
df = pd.read_csv("../data_raw/Superstore.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [12]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [13]:
df.shape

(9994, 21)

In [14]:
df.isnull().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [15]:
df = df.drop_duplicates()

In [16]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [17]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['quarter'] = df['order_date'].dt.quarter

In [18]:
df['profit_margin'] = df['profit'] / df['sales']

In [19]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sub-category,product_name,sales,quantity,discount,profit,year,month,quarter,profit_margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,4,0.1600
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,4,0.3000
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,2,0.4700
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,4,-0.4000
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,4,0.1125

In [20]:
dim_product = df[['product_id', 'product_name', 'category', 'sub-category']].drop_duplicates()
dim_product.head()

,product_id,product_name,category,sub-category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

In [21]:
dim_customer = df[['customer_id', 'customer_name', 'segment']].drop_duplicates()
dim_customer.head()

   customer_id    customer_name    segment
0     CG-12520      Claire Gute   Consumer
2     DV-13045  Darrin Van Huff  Corporate
3     SO-20335   Sean O'Donnell   Consumer
5     BH-11710  Brosina Hoffman   Consumer
12    AA-10480     Andrew Allen   Consumer

In [22]:
dim_date = df[['order_date', 'year', 'month', 'quarter']].drop_duplicates()
dim_date['date_id'] = dim_date.index + 1
dim_date.head()

   order_date  year  month  quarter  date_id
0  2016-11-08  2016     11        4        1
2  2016-06-12  2016      6        2        3
3  2015-10-11  2015     10        4        4
5  2014-06-09  2014      6        2        6
12 2017-04-15  2017      4        2       13

In [23]:
dim_region = df[['region', 'country', 'state', 'city']].drop_duplicates()
dim_region['region_id'] = dim_region.index + 1
dim_region.head()

   region        country           state             city  region_id
0   South  United States        Kentucky        Henderson          1
2    West  United States      California      Los Angeles          3
3   South  United States         Florida  Fort Lauderdale          4
12  South  United States  North Carolina          Concord         13
13   West  United States      Washington          Seattle         14

In [24]:
fact_sales = df.merge(
    dim_date,
    on=['order_date', 'year', 'month', 'quarter'],
    how='left'
)

fact_sales = fact_sales.merge(
    dim_region[['region_id', 'region', 'country', 'state', 'city']],
    on=['region', 'country', 'state', 'city'],
    how='left'
)

fact_sales = fact_sales[['order_id', 'sales', 'profit', 'quantity',
                         'date_id', 'product_id', 'customer_id', 'region_id']]

fact_sales.head()

,order_id,sales,profit,quantity,date_id,product_id,customer_id,region_id
0,CA-2016-152156,261.9600,41.9136,2,1,FUR-BO-10001798,CG-12520,1
1,CA-2016-152156,731.9400,219.5820,3,1,FUR-CH-10000454,CG-12520,1
2,CA-2016-138688,14.6200,6.8714,2,3,OFF-LA-10000240,DV-13045,3
3,US-2015-108966,957.5775,-383.0310,5,4,FUR-TA-10000577,SO-20335,4
4,US-2015-108966,22.3680,2.5164,2,4,OFF-ST-10000760,SO-20335,4

In [25]:
fact_sales.to_csv("../data_cleaned/fact_sales.csv", index=False)
dim_product.to_csv("../data_cleaned/dim_product.csv", index=False)
dim_customer.to_csv("../data_cleaned/dim_customer.csv", index=False)
dim_date.to_csv("../data_cleaned/dim_date.csv", index=False)
dim_region.to_csv("../data_cleaned/dim_region.csv", index=False)

In [27]:
print("ETL completed successfully. Clean CSV files are in /data_cleaned/")

ETL completed successfully. Clean CSV files are in /data_cleaned/

In [28]:

import openpyxl


tables = {
    'fact_sales': fact_sales,
    'dim_product': dim_product,
    'dim_customer': dim_customer,
    'dim_date': dim_date,
    'dim_region': dim_region
}


dict_rows = []

for table_name, table in tables.items():
    for col in table.columns:
        dict_rows.append({
            'table_name': table_name,
            'column_name': col,
            'data_type': str(table[col].dtype),
            'sample_values': ', '.join(map(str, table[col].head(3).values))
        })


data_dictionary = pd.DataFrame(dict_rows)

# Export as Excel
data_dictionary.to_excel("../data_cleaned/data_dictionary.xlsx", index=False)

print("Data dictionary created successfully at /data_cleaned/data_dictionary.xlsx")

KeyboardInterrupt:

In [29]:
# -------------------------------
# CREATE DATA DICTIONARY USING PANDAS ONLY
# -------------------------------

# Dictionary of all tables
tables = {
    'fact_sales': fact_sales,
    'dim_product': dim_product,
    'dim_customer': dim_customer,
    'dim_date': dim_date,
    'dim_region': dim_region
}

dict_rows = []

for table_name, table in tables.items():
    for col in table.columns:
        dict_rows.append({
            'table_name': table_name,
            'column_name': col,
            'data_type': str(table[col].dtype),
            'sample_values': ', '.join(map(str, table[col].head(3).values))
        })

# Convert to DataFrame
data_dictionary = pd.DataFrame(dict_rows)

# Save as CSV instead of Excel
data_dictionary.to_csv("../data_cleaned/data_dictionary.csv", index=False)

print("Data dictionary created successfully at /data_cleaned/data_dictionary.csv")

Data dictionary created successfully at /data_cleaned/data_dictionary.csv